// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: protos/reporting-service/reporting.proto

package reportingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTotalReportsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTotalReportsRequest) Reset() {
	*x = GetTotalReportsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_reporting_service_reporting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalReportsRequest) ProtoMessage() {}

func (x *GetTotalReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reporting_service_reporting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalReportsRequest.ProtoReflect.Descriptor instead.
func (*GetTotalReportsRequest) Descriptor() ([]byte, []int) {
	return file_protos_reporting_service_reporting_proto_rawDescGZIP(), []int{0}
}

type GetTotalReportsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalIncome   int64 `protobuf:"varint,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpenses int64 `protobuf:"varint,2,opt,name=total_expenses,json=totalExpenses,proto3" json:"total_expenses,omitempty"`
	NetSavings    int64 `protobuf:"varint,3,opt,name=net_savings,json=netSavings,proto3" json:"net_savings,omitempty"`
}

func (x *GetTotalReportsResponse) Reset() {
	*x = GetTotalReportsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_reporting_service_reporting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalReportsResponse) ProtoMessage() {}

func (x *GetTotalReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reporting_service_reporting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalReportsResponse.ProtoReflect.Descriptor instead.
func (*GetTotalReportsResponse) Descriptor() ([]byte, []int) {
	return file_protos_reporting_service_reporting_proto_rawDescGZIP(), []int{1}
}

func (x *GetTotalReportsResponse) GetTotalIncome() int64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *GetTotalReportsResponse) GetTotalExpenses() int64 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

func (x *GetTotalReportsResponse) GetNetSavings() int64 {
	if x != nil {
		return x.NetSavings
	}
	return 0
}

type GetReportsByCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReportsByCategoryRequest) Reset() {
	*x = GetReportsByCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_reporting_service_reporting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReportsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportsByCategoryRequest) ProtoMessage() {}

func (x *GetReportsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reporting_service_reporting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetReportsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_reporting_service_reporting_proto_rawDescGZIP(), []int{2}
}

type SpendingByCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category   string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	TotalSpent int64  `protobuf:"varint,2,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
}

func (x *SpendingByCategory) Reset() {
	*x = SpendingByCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_reporting_service_reporting_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendingByCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingByCategory) ProtoMessage() {}

func (x *SpendingByCategory) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reporting_service_reporting_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingByCategory.ProtoReflect.Descriptor instead.
func (*SpendingByCategory) Descriptor() ([]byte, []int) {
	return file_protos_reporting_service_reporting_proto_rawDescGZIP(), []int{3}
}

func (x *SpendingByCategory) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SpendingByCategory) GetTotalSpent() int64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

type GetReportsByCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*SpendingByCategory `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetReportsByCategoryResponse) Reset() {
	*x = GetReportsByCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_reporting_service_reporting_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReportsByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportsByCategoryResponse) ProtoMessage() {}

func (x *GetReportsByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reporting_service_reporting_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportsByCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetReportsByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_reporting_service_reporting_proto_rawDescGZIP(), []int{4}
}

func (x *GetReportsByCategoryResponse) GetList() []*SpendingByCategory {
	if x != nil {
		return x.List
	}
	return nil
}

var File_protos_reporting_service_reporting_proto protoreflect.FileDescriptor

var file_protos_reporting_service_reporting_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69,
	0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x70,
	0x65, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65,
	0x74, 0x5f, 0x73, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x6e, 0x65, 0x74, 0x53, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x12, 0x53, 0x70,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x22, 0x47, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x70,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xb5, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x17,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5b, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x53,
	0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x42, 0x79,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x42, 0x79, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x18,
	0x5a, 0x16, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_reporting_service_reporting_proto_rawDescOnce sync.Once
	file_protos_reporting_service_reporting_proto_rawDescData = file_protos_reporting_service_reporting_proto_rawDesc
)

func file_protos_reporting_service_reporting_proto_rawDescGZIP() []byte {
	file_protos_reporting_service_reporting_proto_rawDescOnce.Do(func() {
		file_protos_reporting_service_reporting_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_reporting_service_reporting_proto_rawDescData)
	})
	return file_protos_reporting_service_reporting_proto_rawDescData
}

var file_protos_reporting_service_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_reporting_service_reporting_proto_goTypes = []any{
	(*GetTotalReportsRequest)(nil),       // 0: GetTotalReportsRequest
	(*GetTotalReportsResponse)(nil),      // 1: GetTotalReportsResponse
	(*GetReportsByCategoryRequest)(nil),  // 2: GetReportsByCategoryRequest
	(*SpendingByCategory)(nil),           // 3: SpendingByCategory
	(*GetReportsByCategoryResponse)(nil), // 4: GetReportsByCategoryResponse
}
var file_protos_reporting_service_reporting_proto_depIdxs = []int32{
	3, // 0: GetReportsByCategoryResponse.list:type_name -> SpendingByCategory
	0, // 1: ReportingService.GetTotalReports:input_type -> GetTotalReportsRequest
	2, // 2: ReportingService.GetReportsSpendingByCategory:input_type -> GetReportsByCategoryRequest
	1, // 3: ReportingService.GetTotalReports:output_type -> GetTotalReportsResponse
	4, // 4: ReportingService.GetReportsSpendingByCategory:output_type -> GetReportsByCategoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_reporting_service_reporting_proto_init() }
func file_protos_reporting_service_reporting_proto_init() {
	if File_protos_reporting_service_reporting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_reporting_service_reporting_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetTotalReportsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_reporting_service_reporting_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetTotalReportsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_reporting_service_reporting_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetReportsByCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_reporting_service_reporting_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SpendingByCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_reporting_service_reporting_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetReportsByCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_reporting_service_reporting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_reporting_service_reporting_proto_goTypes,
		DependencyIndexes: file_protos_reporting_service_reporting_proto_depIdxs,
		MessageInfos:      file_protos_reporting_service_reporting_proto_msgTypes,
	}.Build()
	File_protos_reporting_service_reporting_proto = out.File
	file_protos_reporting_service_reporting_proto_rawDesc = nil
	file_protos_reporting_service_reporting_proto_goTypes = nil
	file_protos_reporting_service_reporting_proto_depIdxs = nil
}
