// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"github.com/google/uuid"
)

type User struct {
	ID       uuid.UUID
	UserName string
	Password string
	Email    string
}
