service:
  host: localhost
  port: 8005
 
kafka:
  host: broker
  port: 9092
  topic: budgets

file:
  cert: ./tls/cert.pem
  key: ./tls/key.pem
  
email:
  from: mahkamovahadija1810@gmail.com
  password: cbgm zcrv kxnx mtin